// Generated by https://quicktype.io

export interface GoogleSignResponse {
    Ca?: string
    xc?: TokenObj
    wt?: Wt
    googleId?: string
    tokenObj?: TokenObj
    tokenId?: string
    accessToken?: string
    profileObj?: ProfileObj
}

export interface ProfileObj {
    googleId: string
    imageUrl: string
    email: string
    name: string
    givenName: string
    familyName: string
}

export interface TokenObj {
    token_type: string
    access_token: string
    scope: string
    login_hint: string
    expires_in: number
    id_token: string
    session_state: SessionState
    first_issued_at: number
    expires_at: number
    idpId: string
}

export interface SessionState {
    extraQueryParams: ExtraQueryParams
}

export interface ExtraQueryParams {
    authuser: string
}

export interface Wt {
    NT: string
    Ad: string
    rV: string
    uT: string
    hK: string
    cu: string
}

// Generated by https://quicktype.io

export interface CalendarListResult {
    result: Result
    body: string
    headers: Headers
    status: number
    statusText: null
}

export interface Headers {
    'cache-control': string
    'content-encoding': string
    'content-length': string
    'content-type': string
    date: string
    expires: string
    server: string
    vary: string
}

export interface Result {
    kind: string
    etag: string
    nextSyncToken?: string | undefined
    items: Calendar[]
}

export interface Calendar {
    kind: string
    etag: string
    id: string
    summary: string
    location?: string
    timeZone?: TimeZone
    colorId?: string
    backgroundColor: string
    foregroundColor: string
    accessRole: string
    defaultReminders: DefaultReminder[]
    conferenceProperties?: ConferenceProperties
    description?: string
    selected?: boolean
    summaryOverride?: string
    primary?: boolean
}

export interface ConferenceProperties {
    allowedConferenceSolutionTypes: AllowedConferenceSolutionType[]
}

export enum AllowedConferenceSolutionType {
    HangoutsMeet = 'hangoutsMeet',
}

export interface DefaultReminder {
    method: string
    minutes: number
}

export enum TimeZone {
    AmericaArgentinaBuenosAires = 'America/Argentina/Buenos_Aires',
    UTC = 'UTC',
}

// Generated by https://quicktype.io

export interface CalendarItems {
    kind: Kind
    etag: string
    id: string
    summary: string
    location?: string
    timeZone: TimeZone
    colorId: string
    backgroundColor: string
    foregroundColor: ForegroundColor
    accessRole: string
    defaultReminders: DefaultReminder[]
    conferenceProperties: ConferenceProperties
    description?: string
    selected?: boolean
    summaryOverride?: string
    primary?: boolean
}

export interface ConferenceProperties {
    allowedConferenceSolutionTypes: AllowedConferenceSolutionType[]
}

export interface DefaultReminder {
    method: string
    minutes: number
}

export enum ForegroundColor {
    Ffffff = '#ffffff',
    The000000 = '#000000',
}

export enum Kind {
    CalendarCalendarListEntry = 'calendar#calendarListEntry',
}
